---
# defaults file for instance

# This specifies what the role should do; the choices are
#
#   create: creates the instance
#   start: starts the instance
#   stop: stops the instance
#   delete: deletes the instance

aws_instance_operation: ""

######## These are the same variables used by the environ role - start ########

# These are the AWS credentials.

####aws_access_key_id: ""
####aws_secret_access_key: ""

# This is used to prefix several of the AWS resource names (see below).

####aws_resource_name_prefix: aws

# These specify the AWS region and availability zone.

####aws_region: us-east-2

# These are defined using aws_resource_name_prefix as the prefix.  So, there is no need to change these definitions.

####aws_vpc_name: "{{ aws_resource_name_prefix }}-vpc"
####aws_subnet_name: "{{ aws_resource_name_prefix }}-subnet"
####aws_igw_name: "{{ aws_resource_name_prefix }}-igw"
####aws_securitygroup_name: "{{ aws_resource_name_prefix }}-securitygroup"

######## These are the same variables used by the environ role - end ########

#aws_instance:
#  aws_tags:
#    instance_hvar_os_type: Linux
#    instance_hvar_basename: myawsinstance
#    instance_hvar_infra_provider: aws
#    instance_hvar_define_hostname: true
#    instance_hvar_update_etchosts_localhost: false
#  aws_instance_type: t2.xlarge
#  aws_image_id: ami-009ed7fcb93e10f3a
#  aws_assign_public_ip: yes
#  aws_volume_list:
#    - device_name: /dev/sda1
#      ebs:
#        volume_size: 50
#        delete_on_termination: True

aws_keypair: ""
aws_route53_zone: ""

aws_linux_ansible_user: "ec2-user"

aws_windows_ansible_user: "Administrator"
aws_windows_ansible_password: ""
