---
# tasks file for environ

- name: Print requested operation
  ansible.builtin.debug:
    msg: "Requested operation: {{ aws_env_operation }}"
#    verbosity: 1

- name: Ensure the AWS environment is created
  include_tasks:
    file: env_create.yml
  when: (aws_env_operation | lower) == "create"

- name: Ensure the AWS environment is deleted
  include_tasks:
    file: env_delete.yml
  when: (aws_env_operation | lower) == "delete"
