---
- name: get instance info
  amazon.aws.ec2_instance_info:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    filters:
      "tag:Name": "{{ aws_base_name }}-{{ aws_instance.ansible_instance_shortname }}"
    region: "{{ aws_region }}"
  register: instance_info

- name: Block to start the instance
  block:

    - name: print instance info
      debug:
        var: instance_info.instances[0]
        verbosity: 1

    - name: print instance info id
      debug:
        msg: "Starting instance {{ inventory_hostname }} with instand_id:  {{ instance_info.instances[0].instance_id }}"

    - name: stop instances
      amazon.aws.ec2_instance:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        instance_ids: "{{ instance_info.instances[0].instance_id }}"
        state: started

  when: instance_info.instances[0] is defined
