---
# tasks file for instance

- name: Ensure the instance is created
  ansible.builtin.include_tasks:
    file: instance_create.yml
  when: (aws_instance_operation | lower) == "create"

- name: Ensure the instance is stopped
  ansible.builtin.include_tasks:
    file: instance_stop.yml
  when: (aws_instance_operation | lower) == "stop"

- name: Ensure the instance is started
  ansible.builtin.include_tasks:
    file: instance_start.yml
  when: (aws_instance_operation | lower) == "start"

- name: Ensure the instance is deleted
  ansible.builtin.include_tasks:
    file: instance_delete.yml
  when: (aws_instance_operation | lower) == "delete"
